CREATE TABLE IF NOT EXISTS projects(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text not null CHECK (name <> ''),
  priority integer not NULL,
  description text,
  deliverydate date not NULL
);

CREATE table if NOT EXISTS tasks(
  id INTEGER PRIMARY KEY generated by DEFAULT as IDENTITY,
  name text not NULL CHECK (name <> ''),
  done boolean,
  projectId INTEGER REFERENCES projects(id)
);

insert into projects(name, priority, description, deliverydate)
 VALUES('Sistema de facturacion',1,'desarrollado en laravel y vuejs', '2020-02-28'),
 ('Sistema de delivery',1,'desarrollado en laravel y vuejs', '2019-02-28'),
 ('app de ventas',3,'desarrollado en dart y flutter', '2020-05-28'),
 ('Sistema de escritorio',2,'desarrollado en java', '2019-08-28');

 insert into tasks(name, done, projectId)
 VALUES('modelo de negocio', false, 1),
 ('UI and UX', false, 2),
 ('fronted', false, 1),
 ('peticiones ajax single page', false, 3),
 ('backend', false, 4);